로그인
HandTris/BE-HandTris pull request #22
Opened 2024-06-20 13:21 UTC by thun0514

> Closes #20 

## PR 타입 (하나 이상의 PR 타입 선택)
- [X] 기능 추가
- [X] 기능 수정
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 설정 변경 (Config Class)
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 배포환경
- [ ] 문서 수정 (ex. README)

## 반영 브랜치
#20 

## 반영 사항
- 로그인 기능 추가
## 유의 사항

## 관련이슈

## 참여자
- @thun0514

2024-06-20 14:13 UTC, seonghoo1217 requested changes

2024-06-20 14:13 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +            throw new IllegalArgumentException("비밀번호가 일치하지 않습니다.");
Custom Exception으로 변경해주세요

2024-06-20 14:13 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +        data.setUsername(memberRequest.getUsername());
Setter 삭제 해주세요

2024-06-20 14:13 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/Member.java
> +@Setter
Setter 삭제해주세요

2024-06-20 14:13 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/global/config/Security/SecurityConfig.java
> +                        .anyRequest().permitAll()
테스트용인가요? 만약아니라면, 회원가입과 로그인을 제외하곤 닫아주세요

2024-06-20 14:13 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/presentation/controller/AuthController.java
> +    public ResponseEntity<String> signup(@RequestBody MemberRequest memberRequest) {
봉투패턴 객체를 사용해주세요

2024-06-20 14:13 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/presentation/dto/request/MemberRequest.java
> +@Setter
DTO는 Record 타입을 사용하는 것을 권장합니다.

2024-06-20 15:35 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +            throw new IllegalArgumentException("비밀번호가 일치하지 않습니다.");
변경 후 '비밀번호 미일치', '동일 아이디', '동일 닉네임' 모두 관리했습니다.

2024-06-20 15:35 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +        data.setUsername(memberRequest.getUsername());
수정 했습니다.

2024-06-20 15:36 UTC, thun0514 commented on src/main/java/jungle/HandTris/domain/Member.java
> +@Setter
삭제 후 3개의 매개변수를 받는 생성자로 수정했습니다.

2024-06-20 15:37 UTC, thun0514 commented on src/main/java/jungle/HandTris/global/config/Security/SecurityConfig.java
> +                        .anyRequest().permitAll()
테스트용으로 모든 경로의 접근을 허용했는데 '메인페이지', '회원가입', '로그인' 을 제외한 모든 경로에 인가된 사용자만 받게끔 수정했습니다.

2024-06-20 15:37 UTC, thun0514 commented on src/main/java/jungle/HandTris/presentation/controller/AuthController.java
> +    public ResponseEntity<String> signup(@RequestBody MemberRequest memberRequest) {
수정 했습니다.

2024-06-20 15:37 UTC, thun0514 commented on src/main/java/jungle/HandTris/presentation/dto/request/MemberRequest.java
> +@Setter
수정했습니다. 한결 보기 좋네요.

2024-06-20 15:42 UTC, seonghoo1217 requested changes

2024-06-20 15:42 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +            throw new CustomException("이미 존재하는 닉네임 입니다.");
`ErrorCode.class` 사용해서 에러메시지 관리해주세요

2024-06-20 15:42 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/Member.java
> +@NoArgsConstructor
NoArgsConstructor option에 Access PROTECTD로 구성해주세요

2024-06-20 15:42 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/exception/CustomException.java
> +    }
해당부분은 없어도 될것같습니다 위의 ErrorCode 리뷰와 동일합니다

2024-06-20 15:42 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/exception/CustomException.java
> +@NoArgsConstructor
해당 어노테이션은 없어도 될 것같습니다.

2024-06-20 15:47 UTC, thun0514 commented on src/main/java/jungle/HandTris/domain/Member.java
> +@NoArgsConstructor
변경 완료했습니다

2024-06-20 16:08 UTC, thun0514 commented on src/main/java/jungle/HandTris/domain/exception/CustomException.java
> +@NoArgsConstructor
삭제했습니다

2024-06-20 16:08 UTC, thun0514 commented on src/main/java/jungle/HandTris/domain/exception/CustomException.java
> +    }
변경했습니다.

2024-06-20 16:08 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +            throw new CustomException("이미 존재하는 닉네임 입니다.");
변경했습니다.

2024-06-20 16:53 UTC, seonghoo1217 requested changes

2024-06-20 16:53 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/repo/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long> {
OCP 원칙을 준수하려면 JpaRepository를 상속받는것이아닌 상위 클래스인 Repository를 상속받도록 바꿔주세요

2024-06-20 16:53 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/exception/CustomException.java
> +}
Exception의 이름이 부정확합니다

그리고 ErrorCode의 사용방법이 잘못된것같습니다.
ErrorCode는 Enum타입으로 에러를 열거형으로 관리하기위해 사용하는 클래스입니다.

2024-06-21 05:41 UTC, thun0514 commented on src/main/java/jungle/HandTris/domain/repo/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long> {
수정했습니다

2024-06-21 11:15 UTC, thun0514 commented on src/main/java/jungle/HandTris/domain/exception/CustomException.java
> +}
각각의 예외처리에 대한 클래스명을 직관적으로 변경했습니다.

2024-06-21 12:09 UTC, seonghoo1217 approved these changes
LGTM

2024-06-21 12:09 UTC, merged