#19
HandTris/BE-HandTris pull request #25
Opened 2024-06-21 07:22 UTC by forrest1398

> Closes #{이슈_번호}

## PR 타입 (하나 이상의 PR 타입 선택)
- [x] 기능 추가
- [ ] 기능 수정
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 설정 변경 (Config Class)
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 배포환경
- [ ] 문서 수정 (ex. README)

## 반영 브랜치
#19
## 반영 사항
전적, 게임 관련 API를 구현

## 유의 사항
API 별 예외처리
1. 전적 및 통계
    - 존재하지 않는 사용자
    - 존재하지 않는 전적 
2. 게임 목록 조회
3. 게임 생성
    - 입력된 카테고리 검증
    - 입력된 총 인원 검증
4. 게임 입장
    - 이미 진행중인 게임
    - 참가인원이 꽉 찬 게임
    - 존재하지 않는 게임
5. 게임 나가기
    - 이미 진행중인 게임
    - 존재하지 않는 게임
6. 게임 삭제
    - 존재하지 않는 게임

## 관련이슈

## 참여자
- @forrest1398

2024-06-21 07:58 UTC, seonghoo1217 requested changes

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/GameService.java
> +public class GameService {
`@Transactional` 추가해주세요

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/GameService.java
> +    }
생성에 대해서는 Entity 전체를 반환하기 보단 `UUID`와 같은 보조키를 Return하는게 좋아보입니다.

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/GameService.java
> +            throw new GameNotFoundException();
`orElseThrow`를 사용해보시는걸 추천합니다

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/GameService.java
> +            throw new GameNotFoundException();
exist보단 findBy가 더 적합해보입니다

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +}
MemberRecord에 대한 도메인은 MemberRecord Layer로 분리해주세요

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/Game.java
> +@NoArgsConstructor
Access=Protected Option을 사용해주시고 공부해서 wiki에 작성해주세요

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/Game.java
> +        this.gameCategory = GameCategory.valueOf(GameCategory.class, gameDetailReq.getGameCategory());
GameCoategory Enum타입에 대해 굳이 valueOf를 쓴이유가 있을까요?

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/repo/GameRepository.java
> +public interface GameRepository extends JpaRepository<Game, Long> {
OCP 원칙을 준수하도록 Repository를 상속 구현하도록 해주세요

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/domain/repo/GameRepository.java
> +@Repository
Repository에 `@Component`가 달려있기에 별도의 Annotation이 필요없습니다

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/global/exception/GlobalExceptionHandler.java
>          if (exceptionMap.containsKey(e.getClass())) {
주석 삭제해주세요

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/global/validation/EnumValidator.java
> +
무엇을 위한 Validator 클래스인가요?

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/presentation/controller/GameController.java
> +        List<GameDetailRes> gameDetailResList = gameList.stream().map(game -> new GameDetailRes(game)).toList();
코드를 간결화 할 수 있을것 같아요

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/presentation/controller/GameController.java
> +    }
enter는 Patch, levae는 post로 처리한 이유를 설명해주세요

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/presentation/controller/MemberController.java
> +    public ResponseEnvelope<MemberRecordDetailRes> getMemberRecord(@PathVariable("memberNickname") String memberNickname) {
간단히 nickname으로 줄여도 될것같습니다. 관용어, 고유명사 격에 해당하는 용어들은 간결화해주세요

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/presentation/dto/request/GameDetailReq.java
> +@Setter
setter지우고 record타입으로 변경해주세요

2024-06-21 07:58 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/presentation/dto/response/GameDetailRes.java
> +}
DTO는 Record타입 이용해주세요

2024-06-21 11:09 UTC, forrest1398 commented on src/main/java/jungle/HandTris/application/service/GameService.java
> +            throw new GameNotFoundException();
orElseThrow를 사용하면 코드가 간결해지는 것 같아 수정했습니다. 다만, 존재하는지만 확인하는 코드의 기능상 exist가 조금 더 적절하다고 생각했는데, 어떤 부분에서 findBy가 더 적절하다고 생각하시나요?

2024-06-21 11:10 UTC, forrest1398 commented on src/main/java/jungle/HandTris/application/service/GameService.java
> +public class GameService {
수정했습니다!

2024-06-21 11:10 UTC, forrest1398 commented on src/main/java/jungle/HandTris/application/service/GameService.java
> +    }
수정했습니다!

2024-06-21 11:10 UTC, forrest1398 commented on src/main/java/jungle/HandTris/application/service/GameService.java
> +            throw new GameNotFoundException();
수정했습니다!

2024-06-21 11:21 UTC, forrest1398 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +}
수정했습니다!

2024-06-21 11:22 UTC, forrest1398 commented on src/main/java/jungle/HandTris/presentation/controller/GameController.java
> +        List<GameDetailRes> gameDetailResList = gameList.stream().map(game -> new GameDetailRes(game)).toList();
수정했습니다!

2024-06-21 11:28 UTC, forrest1398 commented on src/main/java/jungle/HandTris/presentation/controller/GameController.java
> +    }
enter진행시 Game의 참여인원 필드인 participantCount 하나만 수정되기 때문에 patch 메소드를 사용했습니다.
leave(exit)는 그 의미상 수정하는게 아니라 나간다는 의미의 api이기 때문에 post를 사용했습니다.
이렇게 보니, 둘을 의미상은 post,또는 기능상 patch로 통일시켜야 할 것 같습니다. api는 의미가 중요하다 생각되어 post로 통일하려고 하는데 어떤가요?

2024-06-21 11:30 UTC, forrest1398 commented on src/main/java/jungle/HandTris/presentation/controller/MemberController.java
> +    public ResponseEnvelope<MemberRecordDetailRes> getMemberRecord(@PathVariable("memberNickname") String memberNickname) {
수정했습니다!

2024-06-21 11:35 UTC, forrest1398 commented on src/main/java/jungle/HandTris/presentation/dto/request/GameDetailReq.java
> +@Setter
수정했습니다!

2024-06-21 11:42 UTC, forrest1398 commented on src/main/java/jungle/HandTris/presentation/dto/response/GameDetailRes.java
> +}
수정했습니다.

2024-06-22 05:28 UTC, seonghoo1217 requested changes

2024-06-22 05:28 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/GameImplement.java
> +    }
deleteById보단 delete로 Entity삭제하도록 만들어주세요

2024-06-22 05:28 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/MemberRecordImplement.java
> +public class MemberRecordImplement implements MemberRecordService {
Impl이라는 네이밍 적용해주세요

2024-06-22 05:28 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/MemberRecordImplement.java
> +}
CQS패턴 적용해주세요

2024-06-22 05:38 UTC, forrest1398 commented on src/main/java/jungle/HandTris/domain/Game.java
> +        this.gameCategory = GameCategory.valueOf(GameCategory.class, gameDetailReq.getGameCategory());
RequestBody에서 정상적으로 받아오기 위해서 gameDetailReq의 gameCategory는 String으로 선언했습니다. 때문에 String을 GamCategory Enum타입으로 바꾸기 위해서 사용했습니다.

2024-06-22 05:42 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/GameService.java
> +            throw new GameNotFoundException();
우선 exist와 같은경우 내부적으로 count 쿼리를 날리기에 이미 값이 존재하는지에 대한 분별이 필요할 때 사용하기 좋은 메소드라고 생각합니다.

그렇기에 삭제할 게임이 실제로 존재(find)한다면 지우는게 더적합하다고 생각합니다.

2024-06-22 05:44 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/presentation/controller/GameController.java
> +    }
post로 통일해주세요

2024-06-22 05:51 UTC, forrest1398 commented on src/main/java/jungle/HandTris/application/impl/GameImplement.java
> +    }
수정했습니다.

2024-06-22 05:51 UTC, forrest1398 commented on src/main/java/jungle/HandTris/presentation/controller/GameController.java
> +    }
수정했습니다.

2024-06-22 05:51 UTC, forrest1398 commented on src/main/java/jungle/HandTris/application/impl/MemberRecordImplement.java
> +public class MemberRecordImplement implements MemberRecordService {
수정했습니다.

2024-06-22 05:53 UTC, forrest1398 commented on src/main/java/jungle/HandTris/global/exception/GlobalExceptionHandler.java
>          if (exceptionMap.containsKey(e.getClass())) {
수정했습니다.

2024-06-22 05:54 UTC, forrest1398 commented on src/main/java/jungle/HandTris/global/validation/EnumValidator.java
> +
게임 생성시, 입력된 gamecategory 문자열이 GameCategory Enum에 속해있는지 검사하기 위한 Validator입니다.

2024-06-22 11:18 UTC, seonghoo1217 approved these changes

2024-06-22 11:18 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/MemberImpl.java
> +public class MemberImpl implements MemberService {
ServiceImpl 네이밍으로 바꿔주세요

2024-06-22 13:02 UTC, merged