JWT 생성 및 발급 구현
HandTris/BE-HandTris pull request #37
Opened 2024-06-22 11:43 UTC by thun0514

> Closes #29 

## PR 타입 (하나 이상의 PR 타입 선택)
- [X] 기능 추가
- [ ] 기능 수정
- [ ] 기능 삭제
- [ ] 버그 수정
- [X] 설정 변경 (Config Class)
- [X] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 배포환경
- [ ] 문서 수정 (ex. README)

## 반영 브랜치
#29 
## 반영 사항
- application-jwt.yml로 secretkey와 token expiration 관리
- JWTUtil.java에서 JWT 생성 및 검증 로직 구현
- MemberService.java에서 로그인 성공시 JWT를 Header에 담아서 반환

## 유의 사항

## 관련이슈

## 참여자
- @thun0514

2024-06-22 11:48 UTC, seonghoo1217 requested changes

2024-06-22 11:48 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +    public Long signin (MemberRequest memberRequest, HttpServletResponse response) {
해당방식이 아닌 HttpHeaders를 통해 Controlelr에서 토큰을 전달하도록해주세요

2024-06-22 11:48 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/global/jwt/JWTUtil.java
> +        String bearerToken = request.getHeader(AUTHORIZATION_HEADER);
RefreshToken 생성로직은 배제된건가요?

2024-06-22 12:39 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/service/MemberService.java
> +    public Long signin (MemberRequest memberRequest, HttpServletResponse response) {
Service 레벨에서 로그인 성공시 토큰을 발급하고, Controller 레벨에서 헤더에 담아서 전송하게 변경했습니다.

2024-06-23 08:58 UTC, thun0514 commented on src/main/java/jungle/HandTris/global/jwt/JWTUtil.java
> +        String bearerToken = request.getHeader(AUTHORIZATION_HEADER);
생성 완료했습니다

2024-06-23 10:45 UTC, seonghoo1217 requested changes

2024-06-23 10:45 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/MemberServiceImpl.java
> +    public Pair<Long, String> signin (MemberRequest memberRequest) {
Pair는 어떤 객체인가요?

2024-06-23 10:45 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/MemberServiceImpl.java
> +        member.setRefreshToken(refreshToken);
네이밍을 set이 아닌 update 또는 modify를 사용해주세요

2024-06-23 10:45 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/global/jwt/JWTUtil.java
> +    private static final String BEARER_PREFIX = "Bearer ";
상수값들은 Yaml에 따로 분리해주세요

2024-06-23 10:45 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/global/jwt/JWTUtil.java
> +    }
토큰을 찾지 못하는 경우 Null을 반환하는건가요?

2024-06-23 10:45 UTC, seonghoo1217 commented on src/main/resources/application-jwt.yml
> +    issuer: Handtris
해당 issuer 값은 무슨값인가요?

2024-06-23 10:46 UTC, thun0514 commented on src/main/resources/application-jwt.yml
> +    issuer: Handtris
토큰 발급자입니다

2024-06-23 10:47 UTC, seonghoo1217 commented on src/main/resources/application-jwt.yml
> +    issuer: Handtris
토큰 발급자를 명시적으로 사용해야하는 이유는 무엇인가요?

2024-06-23 10:53 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/impl/MemberServiceImpl.java
> +        member.setRefreshToken(refreshToken);
변경 완료했습니다

2024-06-23 10:54 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/impl/MemberServiceImpl.java
> +    public Pair<Long, String> signin (MemberRequest memberRequest) {
Pair는 다른 두 타입을 넘길 때 사용한 객체입니다.
유저 아이디와 토큰을 넘길 때 사용했습니다.
추후에 MemberDetailRes 객체로 변경 생각 중에 있습니다

2024-06-23 10:56 UTC, thun0514 commented on src/main/resources/application-jwt.yml
> +    issuer: Handtris
현재 발급자가 한 곳 뿐이라 필요유무에 대해 논한다면 필요없겠지만, 추후 확장 가능성에 대해 열어뒀습니다.
또한 보안에 관련하여 issuer를 사용하기도 합니다.
예를 들어 공격자가 토큰을 위조하려고 시도하더라도, issuer 정보가 일치하지 않으면 검증 과정에서 쉽게 탐지될 수 있습니다.

2024-06-23 10:59 UTC, thun0514 commented on src/main/java/jungle/HandTris/global/jwt/JWTUtil.java
> +    }
맞습니다. 헤더에서 토큰을 뽑아오고 해당 토큰이 존재하지 않거나, BEARER_PREFIX로 저장된 'Bearer '로 시작되지 않다면 저희 서비스에서 발급한 토큰이 아니라 판단하여 Null을 반환하도록 했습니다.

2024-06-23 11:19 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/global/jwt/JWTUtil.java
> +    }
그럼 예외를 던지도록 처리하는 방향은 어떨까요?

2024-06-23 11:20 UTC, seonghoo1217 commented on src/main/resources/application-jwt.yml
> +    issuer: Handtris
확인했습니다. 다만 회원을 DB에서 찾는로직은 별개로 동작하는건지 궁금합니다.

2024-06-23 11:24 UTC, thun0514 commented on src/main/java/jungle/HandTris/global/jwt/JWTUtil.java
> +    private static final String BEARER_PREFIX = "Bearer ";
다른 값들은 Yaml에 분리를 했지만, `private static final String BEARER_PREFIX = "Bearer "` 에 대해선 문자 뒤 공백이 있다보니 변수참조 형식으로 할 수 없는 거 같습니다.

2024-06-23 11:28 UTC, thun0514 commented on src/main/java/jungle/HandTris/global/jwt/JWTUtil.java
> +    private static final String BEARER_PREFIX = "Bearer ";
BEARER_PREFIX도 yaml에 분리하고 생성시 따로 공백 한 칸 추가하는 방식으로 변경했습니다

2024-06-23 11:46 UTC, thun0514 commented on src/main/java/jungle/HandTris/global/jwt/JWTUtil.java
> +    }
확인했습니다

2024-06-23 11:46 UTC, thun0514 commented on src/main/resources/application-jwt.yml
> +    issuer: Handtris
회원을 DB에서 찾는 로직과 issuer와는 무관합니다

2024-06-23 12:24 UTC, seonghoo1217 approved these changes
LGTM 👍

2024-06-23 12:25 UTC, merged