회원정보 기능 추가
HandTris/BE-HandTris pull request #79
Opened 2024-06-30 13:31 UTC by thun0514

> Closes #74 

## PR 타입 (하나 이상의 PR 타입 선택)
- [X] 기능 추가
- [ ] 기능 수정
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 설정 변경 (Config Class)
- [X] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 배포환경
- [ ] 문서 수정 (ex. README)

## 반영 브랜치
#74 
## 반영 사항
- MyPage API 추가
- 내 정보 수정 기능 추가
## 유의 사항

## 관련이슈

## 참여자
- @thun0514

2024-07-01 02:26 UTC, seonghoo1217 requested changes

2024-07-01 02:26 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/MemberInfoServiceImpl.java
> +
추후 Migration 해주세여 현재 어노테이션에서 토큰정보 parsing해오는걸로 변경되었습니다.

2024-07-01 02:26 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/MemberInfoServiceImpl.java
> +            }
이외의 확장자타입은 처리하지않기 위함인가요?

2024-07-01 02:26 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/MemberInfoServiceImpl.java
> +                throw new InvalidImageTypeException();
상수값으로 image를 꺼내서 비교해야하나요?

2024-07-01 02:26 UTC, seonghoo1217 commented on src/main/java/jungle/HandTris/application/impl/S3UploaderServiceImpl.java
> +    }
현재 반환값이 어떤형태로 나오는지 알려주실 수 있나요?

2024-07-01 02:33 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/impl/MemberInfoServiceImpl.java
> +            }
이미지 파일 중에서도 GIF도 있기에 지정한 확장자만 받기 위해 처리했습니다.

2024-07-01 02:34 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/impl/MemberInfoServiceImpl.java
> +
알겠습니다

2024-07-01 02:34 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/impl/MemberInfoServiceImpl.java
> +                throw new InvalidImageTypeException();
MIME 타입으로 들어온 파일의 시작이 "image/" 로 시작하는지 확인하는 작업입니다.

2024-07-01 07:35 UTC, thun0514 commented on src/main/java/jungle/HandTris/application/impl/S3UploaderServiceImpl.java
> +    }
```
https://handtris.s3.ap-northeast-2.amazonaws.com/profile/12088f8b-d2e1-436f-a7b2-61f77a79f885images.jpg
```

2024-07-02 05:29 UTC, seonghoo1217 approved these changes
LGTM

2024-07-02 05:29 UTC, merged